apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: ${LOKI_URL}
    jsonData:
      manageAlerts: false

  - name: Tempo
    type: tempo
    access: proxy
    url: ${TEMPO_URL}
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
      serviceMap:
        datasourceUid: prometheus
