services:
  loki:
    env_file:
      - deploy/prod/.env
    environment:
      LOKI_S3_BUCKET: "${LOKI_S3_BUCKET}"
      LOKI_S3_ENDPOINT: "${LOKI_S3_ENDPOINT}"
      LOKI_S3_ACCESS_KEY: "${LOKI_S3_ACCESS_KEY}"
      LOKI_S3_SECRET_KEY: "${LOKI_S3_SECRET_KEY}"
      LOKI_S3_REGION: "${LOKI_S3_REGION}"