[[servers]]
host = "ad01.banco.local"
port = 636
use_ssl = true
start_tls = false
ssl_skip_verify = false

bind_dn = "CN=svc_grafana_ldap,OU=Service Accounts,DC=banco,DC=local"
bind_password = "${LDAP_BIND_PASSWORD}"

search_filter = "(sAMAccountName=%s)"
search_base_dns = ["DC=banco,DC=local"]

group_search_filter = "(&(objectClass=group)(member=%s))"
group_search_base_dns = ["OU=Groups,DC=banco,DC=local"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email = "mail"

[[servers.group_mappings]]
group_dn = "CN=GG-Grafana-Admins,OU=Groups,DC=banco,DC=local"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "CN=GG-Grafana-Editors,OU=Groups,DC=banco,DC=local"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "CN=GG-Grafana-Viewers,OU=Groups,DC=banco,DC=local"
org_role = "Viewer"

[[servers.group_mappings]]
group_dn = "CN=GG-Grafana-Auditors,OU=Groups,DC=banco,DC=local"
org_role = "Viewer"