[[servers]]
# La IP o nombre del contenedor LDAP falso en la red docker
host = "openldap"
port = 10389
use_ssl = false

# El usuario "Administrador" del LDAP de la imagen rroemhild
bind_dn = "cn=admin,dc=planetexpress,dc=com"
bind_password = "GoodNewsEveryone"

search_filter = "(uid=%s)"
search_base_dns = ["ou=people,dc=planetexpress,dc=com"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "uid"
member_of = "memberOf"
email =  "mail"

[[servers.group_mappings]]
# Si es del grupo admin_staff, es Admin en Grafana
group_dn = "cn=admin_staff,ou=people,dc=planetexpress,dc=com"
org_role = "Admin"

[[servers.group_mappings]]
# Si es de ship_crew, es Lector (Fry, Bender, etc)
group_dn = "cn=ship_crew,ou=people,dc=planetexpress,dc=com"
org_role = "Viewer"